Add support for Rest-connectivity
faktorzehn/gerrit-events pull request #1
Opened 2022-06-20 08:26 UTC by ManuelMuehlberger

Enabling gerrit-events to pull info from gerrit's Rest api. This is mainly intended for connectivity with our [ jira-gerrit](https://github.com/faktorzehn/jira-gerrit-plugin) fork.

2022-06-20 09:19 UTC, f10mlupfer requested changes
noch ein paar Anmerkungen und Gedankenanstösse, was man vielleicht noch anpassen könnte

2022-06-20 09:19 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +  }
das kann raus

2022-06-20 09:19 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +     * @return the password
nicht richtig

2022-06-20 09:19 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +  private final int statusNotFound = 404;
könnte man als static final int STATUS_OK = 200; bspw. definieren, dann kann man sie in der Testklasse auch verwenden

2022-06-20 09:19 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +public class GerritQueryHandlerHttp {
können wir den GerritQueryHandlerHttp von GerritQueryHandler erben lassen? Sparen wir uns da Implementierungen?

2022-06-20 09:19 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +        });
die Methode runQuery ist ja private, da könnte man sich das LineVisitor Interface sparen und anstatt dessen einfach einen Consumer<String> übergeben und in der runQuery dann einfach in der Schleife visitor.accept(String) machen

2022-06-20 09:19 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +        });
und hier dann einfach list::add

2022-06-20 09:19 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +      visitor.visit(jsonArray.getString(i));
visitor.accept(jsonArray.getString(i));
die for Loop könnte man auch noch per Stream machen (kein muss).

2022-06-20 09:19 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +  }
wäre mit Consumer<String> dann überflüssig

2022-06-20 09:19 UTC, f10mlupfer commented on src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttpTest.java
> + */
das braucht es dann auch nicht

2022-06-20 09:19 UTC, f10mlupfer commented on src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttpTest.java
> +    private void urlConversionTest3True() throws Exception {
True bedeutet hier, dass keine Exception geworfen wird? Würde dann eher Success nehmen. Gibt es auch Tests für Failure/Exception? Braucht es das?

2022-06-20 09:19 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +      str.append("&o=ALL_REVISIONS");
macht es ggf. Sinn, diese URL-Parameter ("&o=ALL_REVISIONS") in Konstanten auszulagern? Dann könnte man diese auch u.A. in den Tests verwenden

2022-06-23 07:21 UTC, ManuelMuehlberger commented on src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttpTest.java
> +    private void urlConversionTest3True() throws Exception {
Name wurde umgeändert zu urlConversionTestXSuccess(). Es gibt einen invalidRequestsThrowsTest() um sicher zu stellen, dass wir richtig mit (für den Server) ungültigen Requests umgehen.

2022-06-23 07:40 UTC, ManuelMuehlberger commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +public class GerritQueryHandlerHttp {
Ich weiß nicht, wieviel wir uns da sparen würden: GerritQueryHandler hat ja einige SSH-spezifische Attribute die in den Konstruktoren gesetzt werden. Wenn wir davon dann subclassen, müssen wir ja viele unnötige Attribute setzen? Entweder müssten wir einen neuen leeren Konstruktor hinzufügen, oder wir erstellen eine abstrakte Superklasse.

2022-06-27 06:02 UTC, f10mlupfer requested changes
die Konsanten könnte man noch renamen, ansonsten ok

2022-06-27 06:02 UTC, f10mlupfer commented on src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttpTest.java
> +    private void urlConversionTest3True() throws Exception {
ok

2022-06-27 06:02 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +public class GerritQueryHandlerHttp {
würde ich gut finden (auch generell vielleicht auch nochmal aufzuräumen). Aber im Moment wäre es auch so ok für mich. Ggf. wäre das auch etwas für die TODO Liste im Wiki. Und evtl. fallen dir ja noch mehr Punkte ein, die man dort mit aufnehmen kann

2022-06-27 06:02 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +  static final int statusOk = 200;
Konstanten würde ich komplett groß schreiben. Bspw. STATUS_OK

2022-06-27 06:02 UTC, f10mlupfer commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +  private final String getMessages = "&o=MESSAGES";
auch die hier
ALL_REVISIONS
...

2022-06-29 06:49 UTC, ManuelMuehlberger commented on src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerHttp.java
> +public class GerritQueryHandlerHttp {
Ich habe jetzt schon mal ein bisschen aufgeräumt, werde im Wiki aber auch eine TODO-Sektion aufmachen

2022-07-08 06:35 UTC, merged